class CfgVehicles {
    /* Leopard 1a1 */
    class gm_Leopard1a1_base;
    class gm_ge_army_Leopard1a1_base: gm_Leopard1a1_base {
        ace_refuel_fuelCapacity = 955;
    };
    class gm_Leopard1a1a1_base;
    class gm_ge_army_Leopard1a1a1_base: gm_Leopard1a1a1_base {
        ace_refuel_fuelCapacity = 955;
    };
    class gm_Leopard1a1a2_base;
    class gm_ge_army_Leopard1a1a2_base: gm_Leopard1a1a2_base {
        ace_refuel_fuelCapacity = 955;
    };
    class gm_Leopard1a1a3_base;
    class gm_ge_army_Leopard1a1a3_base: gm_Leopard1a1a3_base {
        ace_refuel_fuelCapacity = 955;
        scope = 2;
        #include "CfgACRE_SEM90_base.inc"
    };
    class gm_Leopard1a1a4_base;
    class gm_ge_army_Leopard1a1a4_base: gm_Leopard1a1a4_base {
        ace_refuel_fuelCapacity = 955;
        scope = 2;
        #include "CfgACRE_SEM90_base.inc"
    };

    /* Leopard 1a3 */
    class gm_Leopard1a3_base;
    class gm_ge_army_Leopard1a3_base: gm_Leopard1a3_base {
        ace_refuel_fuelCapacity = 955;
    };
    class gm_Leopard1a3a1_base;
    class gm_ge_army_Leopard1a3a1_base: gm_Leopard1a3a1_base {
        ace_refuel_fuelCapacity = 955;
    };
    class gm_Leopard1a3a2_base;
    class gm_ge_army_Leopard1a3a2_base: gm_Leopard1a3a2_base {
        ace_refuel_fuelCapacity = 955;
        scope = 2;
        #include "CfgACRE_SEM90_base.inc"
    };
    class gm_Leopard1a3a3_base;
    class gm_ge_army_Leopard1a3a3_base: gm_Leopard1a3a3_base {
        ace_refuel_fuelCapacity = 955;
        scope = 2;
        #include "CfgACRE_SEM90_base.inc"
    };

    /*TODO Leopard 1a5*/
};
