class CfgVehicles {
    /* Leopard 1a1 */
    class gm_leopard1a1_base;
    class gm_ge_army_leopard1a1_base: gm_leopard1a1_base {
        ace_refuel_fuelCapacity = 955;
        #include "CfgACRE_SEM25_base.inc"
    };
    class gm_leopard1a1a1_base;
    class gm_ge_army_leopard1a1a1_base: gm_leopard1a1a1_base {
        ace_refuel_fuelCapacity = 955;
        #include "CfgACRE_SEM25_base.inc"
    };
    class gm_leopard1a1a2_base;
    class gm_ge_army_leopard1a1a2_base: gm_leopard1a1a2_base {
        ace_refuel_fuelCapacity = 955;
        #include "CfgACRE_SEM25_base.inc"
    };
    class gm_leopard1a1a3_base;
    class gm_ge_army_leopard1a1a3_base: gm_leopard1a1a3_base {
        ace_refuel_fuelCapacity = 955;
        #include "CfgACRE_SEM90_base.inc"
    };
    class gm_ge_army_leopard1a1a3: gm_ge_army_leopard1a1a3_base {
        scope = 2;
        scopeCurator = 2;
    };
    class gm_leopard1a1a4_base;
    class gm_ge_army_leopard1a1a4_base: gm_leopard1a1a4_base {
        ace_refuel_fuelCapacity = 955;
        #include "CfgACRE_SEM90_base.inc"
    };
    class gm_ge_army_leopard1a1a4: gm_ge_army_leopard1a1a4_base {
        scope = 2;
        scopeCurator = 2;
    };

    /* Leopard 1a3 */
    class gm_leopard1a3_base;
    class gm_ge_army_leopard1a3_base: gm_leopard1a3_base {
        ace_refuel_fuelCapacity = 955;
        #include "CfgACRE_SEM25_base.inc"
    };
    class gm_leopard1a3a1_base;
    class gm_ge_army_leopard1a3a1_base: gm_leopard1a3a1_base {
        ace_refuel_fuelCapacity = 955;
        #include "CfgACRE_SEM25_base.inc"
    };
    class gm_leopard1a3a2_base;
    class gm_ge_army_leopard1a3a2_base: gm_leopard1a3a2_base {
        ace_refuel_fuelCapacity = 955;
        #include "CfgACRE_SEM90_base.inc"
    };
    class gm_ge_army_leopard1a3a2: gm_ge_army_leopard1a3a2_base {
        scope = 2;
        scopeCurator = 2;
    };
    class gm_leopard1a3a3_base;
    class gm_ge_army_leopard1a3a3_base: gm_leopard1a3a3_base {
        ace_refuel_fuelCapacity = 955;
        #include "CfgACRE_SEM90_base.inc"
    };
    class gm_ge_army_leopard1a3a3: gm_ge_army_leopard1a3a3_base {
        scope = 2;
        scopeCurator = 2;
    };

    /* Leopard 1a5 */
    class gm_leopard1a5_base;
    class gm_ge_army_leopard1a5_base: gm_leopard1a5_base {
        ace_refuel_fuelCapacity = 955;
        #include "CfgACRE_SEM25_base.inc"
    };

    class gm_leopard1a5a1_base;
    class gm_ge_army_leopard1a5a1_base: gm_leopard1a5a1_base {
        ace_refuel_fuelCapacity = 955;
        #include "CfgACRE_SEM90_base.inc"
    };
    class gm_ge_army_leopard1a5a1: gm_ge_army_leopard1a5a1_base {
        scope = 2;
        scopeCurator = 2;
    };
};
