class cfgVehicles {
	class gm_marder1a1a_base;
	class gm_ge_army_marder1a1a_base: gm_marder1a1a_base {
		ace_refuel_fuelCapacity = 650;
        ace_refuel_canReceive = 1;
        ace_refuel_flowRate = 1;
        fuelCapacity = "650 * 0.165";
		#include "CfgACRE_SEM25_base.inc"
	};
	class gm_marder1a1plus_base;
	class gm_ge_army_marder1a1plus_base: gm_marder1a1plus_base {
		ace_refuel_fuelCapacity = 650;
        ace_refuel_canReceive = 1;
        ace_refuel_flowRate = 1;
        fuelCapacity = "650 * 0.165";
		#include "CfgACRE_SEM25_base.inc"
	};
	class gm_marder1a2_base;
	class gm_ge_army_marder1a2_base: gm_marder1a2_base {
		ace_refuel_fuelCapacity = 650;
        ace_refuel_canReceive = 1;
        ace_refuel_flowRate = 1;
        fuelCapacity = "650 * 0.165";
		#include "CfgACRE_SEM25_base.inc"
	};
};