class CfgMods {
    class PREFIX {
        author = "GME Team";
        dir = "@gme";
        name = "GME v1.1.23";
        picture = "gme\addons\main\logo_gme_ca.paa";
        hidePicture = 1;
        hideName = 1;
        actionName = "Website";
        action = "https://vpzbrig21.de";
        description = "Bugtracker: https://github.com/vpzbrig21/gme/issues";
        tooltip = "GME";
        tooltipOwned = "GME Owned";
        overview = "Global Mobilization Enhancement tries to provide full compatibility for the ACE3 and ACRE2 modifications.";
    };
};
