class CfgVehicles {
    /* Leopard 1a3 */
    class gm_ge_army_leopard1a3a3_base;
    class gme_ge_army_leopard1a3a3_pb21_base: gm_ge_army_leopard1a3a3_base {
        displayName = "KPz Leopard 1A3A3 - PzBrig21";
        gm_InsigniasDefaultUnit = "gme_units_ge_pzgrenbtl212_col";
		gm_TacticalSignsDefaultPostIcon = "203";
		gm_TacticalSignsDefaultPreIcon = "2";
        #include "CfgACRE_SEM90_base.inc"

        //Empty
        maximumLoad = 10000;
        class TransportWeapons {};
		class TransportMagazines {};
		class TransportItems {};
		class TransportBackpacks {};
    };
    class gme_ge_army_leopard1a3a3_pb21: gme_ge_army_leopard1a3a3_pb21_base {
        displayName = "KPz Leopard 1A3A3 - PzBrig21";
        scope = 2;
        scopeCurator = 2;
    };

    /* Leopard 1a5 */
    class gm_ge_army_leopard1a5a1_base;
    class gme_ge_army_leopard1a5a1_pb21_base: gm_ge_army_leopard1a5a1_base {
        displayName = "KPz Leopard 1A5A1 - PzBrig21";
        gm_InsigniasDefaultUnit = "gme_units_ge_pzgrenbtl212_col";
		gm_TacticalSignsDefaultPostIcon = "203";
		gm_TacticalSignsDefaultPreIcon = "2";
        #include "CfgACRE_SEM90_base.inc"

        //Empty
        maximumLoad = 10000;
        class TransportWeapons {};
		class TransportMagazines {};
		class TransportItems {};
		class TransportBackpacks {};
    };
    class gme_ge_army_leopard1a5a1_pb21: gme_ge_army_leopard1a5a1_pb21_base {
        displayName = "KPz Leopard 1A5A1 - PzBrig21";
        scope = 2;
        scopeCurator = 2;
    };

    // Alfa Zug
    class gme_ge_army_leopard1a5a1_pb21_a: gme_ge_army_leopard1a5a1_pb21_base {
        displayName = "KPz Leopard 1A5A1 - I/2./203 A";
        scope = 2;
        scopeCurator = 2;
        gm_LicensePlateDefaultDigits = "Y-297005";
		gm_TacticalNumbersDefaultNumber = "210";
		gm_InsigniasDefaultFormation = "gm_insignia_formation_A_yel";
    };
    class gme_ge_army_leopard1a5a1_pb21_a1: gme_ge_army_leopard1a5a1_pb21_base {
        displayName = "KPz Leopard 1A5A1 - I/2./203 A1";
        scope = 2;
        scopeCurator = 2;
        gm_LicensePlateDefaultDigits = "Y-250405";
		gm_TacticalNumbersDefaultNumber = "211";
		gm_InsigniasDefaultFormation = "gm_insignia_formation_A1_yel";
    };
    class gme_ge_army_leopard1a5a1_pb21_a2: gme_ge_army_leopard1a5a1_pb21_base {
        displayName = "KPz Leopard 1A5A1 - I/2./203 A2";
        scope = 2;
        scopeCurator = 2;
        gm_LicensePlateDefaultDigits = "Y-245002";
		gm_TacticalNumbersDefaultNumber = "212";
		gm_InsigniasDefaultFormation = "gm_insignia_formation_A2_yel";
    };
    class gme_ge_army_leopard1a5a1_pb21_a3: gme_ge_army_leopard1a5a1_pb21_base {
        displayName = "KPz Leopard 1A5A1 - I/2./203 A3";
        scope = 2;
        scopeCurator = 2;
        gm_LicensePlateDefaultDigits = "Y-233805";
		gm_TacticalNumbersDefaultNumber = "213";
		gm_InsigniasDefaultFormation = "gm_insignia_formation_A3_yel";
    };

    // Bravo Zug
    class gme_ge_army_leopard1a5a1_pb21_b: gme_ge_army_leopard1a5a1_pb21_base {
        displayName = "KPz Leopard 1A5A1 - II/2./203 B";
        scope = 2;
        scopeCurator = 2;
        gm_LicensePlateDefaultDigits = "Y-215761";
		gm_TacticalNumbersDefaultNumber = "220";
		gm_InsigniasDefaultFormation = "gm_insignia_formation_B_yel";
    };
    class gme_ge_army_leopard1a5a1_pb21_b1: gme_ge_army_leopard1a5a1_pb21_base {
        displayName = "KPz Leopard 1A5A1 - II/2./203 B1";
        scope = 2;
        scopeCurator = 2;
        gm_LicensePlateDefaultDigits = "Y-213986";
		gm_TacticalNumbersDefaultNumber = "221";
		gm_InsigniasDefaultFormation = "gm_insignia_formation_B1_yel";
    };
    class gme_ge_army_leopard1a5a1_pb21_b2: gme_ge_army_leopard1a5a1_pb21_base {
        displayName = "KPz Leopard 1A5A1 - II/2./203 B2";
        scope = 2;
        scopeCurator = 2;
        gm_LicensePlateDefaultDigits = "Y-288449";
		gm_TacticalNumbersDefaultNumber = "222";
		gm_InsigniasDefaultFormation = "gm_insignia_formation_B2_yel";
    };
    class gme_ge_army_leopard1a5a1_pb21_b3: gme_ge_army_leopard1a5a1_pb21_base {
        displayName = "KPz Leopard 1A5A1 - II/2./203 B3";
        scope = 2;
        scopeCurator = 2;
        gm_LicensePlateDefaultDigits = "Y-275696";
		gm_TacticalNumbersDefaultNumber = "223";
		gm_InsigniasDefaultFormation = "gm_insignia_formation_B3_yel";
    };

    // Charlie Zug
    class gme_ge_army_leopard1a5a1_pb21_c: gme_ge_army_leopard1a5a1_pb21_base {
        displayName = "KPz Leopard 1A5A1 - III/2./203 C";
        scope = 2;
        scopeCurator = 2;
        gm_LicensePlateDefaultDigits = "Y-275542";
		gm_TacticalNumbersDefaultNumber = "230";
		gm_InsigniasDefaultFormation = "gm_insignia_formation_C_yel";
    };
    class gme_ge_army_leopard1a5a1_pb21_c1: gme_ge_army_leopard1a5a1_pb21_base {
        displayName = "KPz Leopard 1A5A1 - III/2./203 C1";
        scope = 2;
        scopeCurator = 2;
        gm_LicensePlateDefaultDigits = "Y-230558";
		gm_TacticalNumbersDefaultNumber = "231";
		gm_InsigniasDefaultFormation = "gm_insignia_formation_C1_yel";
    };
    class gme_ge_army_leopard1a5a1_pb21_c2: gme_ge_army_leopard1a5a1_pb21_base {
        displayName = "KPz Leopard 1A5A1 - III/2./203 C2";
        scope = 2;
        scopeCurator = 2;
        gm_LicensePlateDefaultDigits = "Y-223329";
		gm_TacticalNumbersDefaultNumber = "232";
		gm_InsigniasDefaultFormation = "gm_insignia_formation_C2_yel";
    };
    class gme_ge_army_leopard1a5a1_pb21_c3: gme_ge_army_leopard1a5a1_pb21_base {
        displayName = "KPz Leopard 1A5A1 - III/2./203 C3";
        scope = 2;
        scopeCurator = 2;
        gm_LicensePlateDefaultDigits = "Y-218704";
		gm_TacticalNumbersDefaultNumber = "233";
		gm_InsigniasDefaultFormation = "gm_insignia_formation_C3_yel";
    };
};
