class CfgMagazineWells {
	class gm_magazineWell_20x139mm {
		gm_magazines[] = {"gm_425Rnd_20x139mm_he_t_dm51","gm_425Rnd_20x139mm_hei_t_dm81","gm_425Rnd_20x139mm_hei_t_dm111","gm_75Rnd_20x139mm_ap_t_dm43","gm_75Rnd_20x139mm_apds_t_dm63"};
		gme_magazines[] = {"gme_320Rnd_20x139mm_hei_t_dm81","gme_180Rnd_20x139mm_apds_t_dm63","gme_400Rnd_20x139mm_hei_t_dm81","gme_100Rnd_20x139mm_apds_t_dm63"};
	};
	class gm_magazineWell_20x139mm_ap {
		gm_magazines[] = {"gm_75Rnd_20x139mm_ap_t_dm43","gm_75Rnd_20x139mm_apds_t_dm63"};
		gme_magazines[] = {"gme_180Rnd_20x139mm_apds_t_dm63","gme_100Rnd_20x139mm_apds_t_dm63"};
	};
	class gm_magazineWell_20x139mm_he {
		gm_magazines[] = {"gm_425Rnd_20x139mm_he_t_dm51","gm_425Rnd_20x139mm_hei_t_dm81","gm_425Rnd_20x139mm_hei_t_dm111"};
		gme_magazines[] = {"gme_320Rnd_20x139mm_hei_t_dm81","gme_400Rnd_20x139mm_hei_t_dm81"};
	};
};