name = "GME"
author = "vPanzerbrigade 21 S4"
prefix = "gme"
mainprefix = "z"

[files]
include = [
    "mod.cpp",
    "READDME.md",
    "AUTHORS.txt",
    "LICENSE",
    "logo_gme_ca.paa"
]

[version]
git_hash = 0

[asc]
enabled = false
exclude = [
    "/xeh_prep.sqf",
]

[hemtt.config]
preset = "Hemtt"

[hemtt.launch]
workshop = [
    "450814997", # CBA_A3's Workshop ID
    "463939057", # ACE3's Workshop ID
]