class CfgVehicles {
	class gm_ge_army_marder1a2_base;
	class pb21_marder1a2_base: gm_ge_army_marder1a2_base {
		maximumLoad = 18000;
	};
	class pb21_marder1a2_c: pb21_marder1a2_base {
		displayName = "SPz Marder 1A2 - III/2./212 C";
		scope = 2;
        scopeCurator = 2;
		gm_LicensePlateDefaultDigits = "Y-284225";
		gm_InsigniasDefaultUnit = "gme_units_ge_pzgrenbtl212_col";
		gm_TacticalNumbersDefaultNumber = "230";
	};
	class pb21_marder1a2_c1: pb21_marder1a2_base {
		displayName = "SPz Marder 1A2 - III/2./212 C1";
		scope = 2;
        scopeCurator = 2;
		gm_LicensePlateDefaultDigits = "Y-268319";
		gm_InsigniasDefaultUnit = "gme_units_ge_pzgrenbtl212_col";
		gm_TacticalNumbersDefaultNumber = "231";
	};
	class pb21_marder1a2_c2: pb21_marder1a2_base {
		displayName = "SPz Marder 1A2 - III/2./212 C2";
		scope = 2;
        scopeCurator = 2;
		gm_LicensePlateDefaultDigits = "Y-283378";
		gm_InsigniasDefaultUnit = "gme_units_ge_pzgrenbtl212_col";
		gm_TacticalNumbersDefaultNumber = "232";
	};
	class pb21_marder1a2_c3: pb21_marder1a2_base {
		displayName = "SPz Marder 1A2 - III/2./212 C3";
		scope = 2;
        scopeCurator = 2;
		gm_LicensePlateDefaultDigits = "Y-274127";
		gm_InsigniasDefaultUnit = "gme_units_ge_pzgrenbtl212_col";
		gm_TacticalNumbersDefaultNumber = "233";
	};
};