class CfgVehicles {
    class gm_kat1_451_cargo_base;
    class gm_ge_army_kat1_451_cargo_base: gm_kat1_451_cargo_base {
        #include "CfgACRE_SEM90_base.inc"
    };
    class gm_kat1_451_container_base;
    class gm_ge_army_kat1_451_container_base: gm_kat1_451_container_base {
        #include "CfgACRE_SEM90_base.inc"
    };
    class gm_kat1_451_reammo_base;
    class gm_ge_army_kat1_451_reammo_base: gm_kat1_451_reammo_base {
        #include "CfgACRE_SEM90_base.inc"
    };
    class gm_kat1_451_refuel_base;
    class gm_ge_army_kat1_451_refuel_base: gm_kat1_451_refuel_base {
        #include "CfgACRE_SEM90_base.inc"
    };
    class gm_kat1_454_cargo_base;
    class gm_ge_army_kat1_454_cargo_base: gm_kat1_454_cargo_base {
        #include "CfgACRE_SEM90_base.inc"
    };
};